---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: zipkin
      name: zipkin
    spec:
    #   type: LoadBalancer
      selector:
        app: zipkin
      ports:
      - name: http
        port: 80
        targetPort: 9411